# Generated by Django 3.1.7 on 2021-02-21 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycalender', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calender',
            old_name='end',
            new_name='end_day',
        ),
        migrations.RenameField(
            model_name='calender',
            old_name='start',
            new_name='start_day',
        ),
    ]
