# Generated by Django 3.1.7 on 2021-02-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mycalender', '0002_auto_20210222_0254'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calender',
            old_name='end_day',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='calender',
            old_name='start_day',
            new_name='start',
        ),
    ]
